//
//  EDSegments.h
//  Moments
//
//  Created by Evan Dekhayser on 12/19/14.
//  Copyright (c) 2014 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface EDSegments : NSObject

// Colors
+ (UIColor*)color;
+ (UIColor*)color3;

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas2;
+ (void)drawCanvas3;
+ (void)drawCanvas4;

@end
